name:  Hello World 1

# Events

on:
  push:
    branches:
      - development

  pull_request:
    branches:
      - development

  workflow_dispatch:

          # Workflow / Jobs

    jobs:
      hello:
        runs-on:  ubuntu-latest
          steps:
            -uses:  actions/checkout@v4
              -name:  Hello
                run:  echo "Hello World"
                  shell:  bash

            hello2:
              runs-on:  ubuntu-latest
                steps:
                  -uses:  actions/checkout@v4
                  -name:  Hello
                   run:  echo "Hello World"
                   shell:  bash


                 
