name: Hello World

# Events

on:
  push:
    branches:
      - development

      pull_request:
        branches:
          - development

workfloew_dispatch:


# Workflow / Jobs

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v4
      - name: Hello
      run: echo "Hello World"
      shell: bash
